<html>
    <head>
        <title>Update Id</title>
        <link rel="stylesheet" href="css/bootstrap.css" />
		 <link rel="stylesheet" href="mystyle.css" />
		 <script type="text/javascript" src="js/jquery.js"></script>
		 <script type="text/javascript" src="js/bootstrap.js"></script>
         
    </head>
	<body>
	<div class="conatiner">
	
	<div class="col-sm-6 ">
	<?php
	$postfix="";
	$prefix="";
	$id_generated="";
	$user_id_generated="";
	$conn=new  mysqli("localhost","root","","online_voting");
	$id=$_GET['id'];
	$select="select * from id_request_tbl where id='$id'";
$run=$conn->query($select);
if($run->num_rows>0)
{
while($row=$run->fetch_array())
{
	$user_email=$row['user_email'];
		$user_city=$row['user_city'];

	
}
switch($user_city)
{
	case 'delhi':
	$prefix="del";
	$rand=rand(9999999,1234567);
	$postfix="xyz";
	$id_generated=$prefix.$rand.$postfix;
	break;
	
	
	case 'mumbai':
	$prefix="mum";
	$rand=rand(9999999,1234567);
	$postfix="xyz";
	$id_generated=$prefix.$rand.$postfix;
	break;
	case 'uttar pradesh':
	$prefix="utt";
	$rand=rand(9999999,1234567);
	$postfix="xyz";
	$id_generated=$prefix.$rand.$postfix;
	break;
	case 'Goa':
	$prefix="goa";
	$rand=rand(9999999,1234567);
	$postfix="xyz";
	$id_generated=$prefix.$rand.$postfix;
	break;
	case 'punjab':
	$prefix="pub";
	$rand=rand(9999999,1234567);
	$postfix="xyz";
	$id_generated=$prefix.$rand.$postfix;
	break;
	
	
	
	
	
	
	
	
	
	
	
}
	
	?>   
	<form method="post">
	    
<div class="form-group">
                        <label for="exampleInputEmail1">User AddharCard</label>
<input type="email" class="form-control"  name="user_email" id="exampleInputEmail1"            
placeholder="Enter email"required readonly value="<?php echo $user_email;?>">                
                 </div>
				 <div class="form-group">
                        <label for="exampleInputmail1">User City</label>
<input type="text" class="form-control"  name="user_city" id="exampleInputEmail1"            
placeholder="Enter the city"required readonly value="<?php echo $user_city;?>">                
                 </div>
				  <div class="form-group">
                        <label for="exampleInputmail1">User ID Generated By System</label>
<input type="text" class="form-control"  name="user_id_generated" id="exampleInputEmail1"            
placeholder="Enter the ID"required readonly value="<?php echo strtoupper ($id_generated);?>">                
                 </div>
				 <div class="form-group">
				 <input type="submit" name="update" value="Update User ID" class="form-control btn btn-success">
				
				 </div>
	
	
	</form>
	<?php
}
else
{
	
	echo "Record Not Found";
}

?>
	</div>
	<div class="col-sm-6 ">
	</div>
	</body>
	</htmL>
	<?php
	if(isset($_POST['update']))
	{
		$user_email=$_POST['user_email'];
	$user_id_generated=$_POST['user_id_generated'];
	$update="update users_db set user_id_generated='$user_id_generated' where user_email='$user_email'";
	$run=$conn->query($update);
	
		if($run)
		{
			$delete="delete from id_request_tbl where user_email='$user_email'";
			$del=$conn->query($delete);
			if($del)
			{
				echo "<script>alert('Update  Successfully and Deleted')</script>";
				echo"<script>window.loaction.href='idrequest.php'></script>";
			}
		}
	else{
		
		
	echo "<script>alert('Something went wrong ! Error')</script>";
	}
	
	}
	?>
	
	
	
	